const INIT = "INIT";
const CLICK_ON_USE_CASE = "CLICK_ON_USE_CASE";
const CLICK_ON_IMAGE = "CLICK_ON_IMAGE";
const SHOW_MORE_VIDEOS = "SHOW_MORE_VIDEOS";

export { INIT, CLICK_ON_USE_CASE, CLICK_ON_IMAGE, SHOW_MORE_VIDEOS };
