const INIT = "INIT";
const CLICK_ON_USE_CASE = "CLICK_ON_USE_CASE";
const CLICK_ON_IMAGE = "CLICK_ON_IMAGE";
const CLICK_ON_SHOW_MORE = "CLICK_ON_SHOW_MORE";

export { INIT, CLICK_ON_USE_CASE, CLICK_ON_IMAGE, CLICK_ON_SHOW_MORE };
